/* =========================================================
   NOW-or-NEVER
   ADMIN SHOP MENUS
   ---------------------------------------------------------
   Server-side protected CRUD for marketplace menu tabs.
   Run this in Supabase SQL editor once.
   ========================================================= */

create table if not exists public.shop_menus (
  id bigint generated by default as identity primary key,
  menu_key text not null unique,
  menu_name text not null,
  icon text not null default '📂',
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_menus_key_check check (menu_key ~ '^[a-z0-9_-]+$'),
  constraint shop_menus_name_check check (length(trim(menu_name)) between 1 and 60)
);

create index if not exists shop_menus_order_idx
  on public.shop_menus (sort_order, id);

insert into public.shop_menus (menu_key, menu_name, icon, sort_order, enabled)
values
  ('textstyle', 'Text Styles', 'Aa', 10, true),
  ('title', 'Titles', '🏷️', 20, true),
  ('crown', 'Crowns', '👑', 30, true),
  ('emoji', 'Emoji FX', '✨', 40, true),
  ('cosmetics', 'Cosmetics', '🎒', 50, true)
on conflict (menu_key) do nothing;

create or replace function public.admin_shop_menus_list()
returns table (
  id bigint,
  menu_key text,
  menu_name text,
  icon text,
  sort_order integer,
  enabled boolean,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ACCESS_REQUIRED';
  end if;

  return query
  select
    m.id,
    m.menu_key,
    m.menu_name,
    m.icon,
    m.sort_order,
    m.enabled,
    m.created_at,
    m.updated_at
  from public.shop_menus m
  order by m.sort_order asc, m.id asc;
end;
$$;

create or replace function public.admin_shop_menu_create(
  p_menu_key text,
  p_menu_name text,
  p_icon text default '📂',
  p_sort_order integer default 100
)
returns public.shop_menus
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.shop_menus;
  v_key text := lower(trim(coalesce(p_menu_key, '')));
  v_name text := trim(coalesce(p_menu_name, ''));
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ACCESS_REQUIRED';
  end if;

  if v_key = '' or v_key !~ '^[a-z0-9_-]+$' then
    raise exception 'INVALID_MENU_KEY';
  end if;

  if v_name = '' or length(v_name) > 60 then
    raise exception 'INVALID_MENU_NAME';
  end if;

  insert into public.shop_menus (menu_key, menu_name, icon, sort_order)
  values (
    v_key,
    v_name,
    coalesce(nullif(trim(p_icon), ''), '📂'),
    coalesce(p_sort_order, 100)
  )
  returning * into v_row;

  return v_row;
exception
  when unique_violation then
    raise exception 'MENU_KEY_ALREADY_EXISTS';
end;
$$;

create or replace function public.admin_shop_menu_update(
  p_id bigint,
  p_menu_key text,
  p_menu_name text,
  p_icon text,
  p_sort_order integer,
  p_enabled boolean
)
returns public.shop_menus
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.shop_menus;
  v_key text := lower(trim(coalesce(p_menu_key, '')));
  v_name text := trim(coalesce(p_menu_name, ''));
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ACCESS_REQUIRED';
  end if;

  if p_id is null then
    raise exception 'INVALID_MENU_ID';
  end if;

  if v_key = '' or v_key !~ '^[a-z0-9_-]+$' then
    raise exception 'INVALID_MENU_KEY';
  end if;

  if v_name = '' or length(v_name) > 60 then
    raise exception 'INVALID_MENU_NAME';
  end if;

  update public.shop_menus
  set
    menu_key = v_key,
    menu_name = v_name,
    icon = coalesce(nullif(trim(p_icon), ''), '📂'),
    sort_order = coalesce(p_sort_order, 100),
    enabled = coalesce(p_enabled, true),
    updated_at = now()
  where id = p_id
  returning * into v_row;

  if not found then
    raise exception 'MENU_NOT_FOUND';
  end if;

  return v_row;
exception
  when unique_violation then
    raise exception 'MENU_KEY_ALREADY_EXISTS';
end;
$$;

create or replace function public.admin_shop_menu_delete(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ACCESS_REQUIRED';
  end if;

  delete from public.shop_menus where id = p_id;

  if not found then
    raise exception 'MENU_NOT_FOUND';
  end if;

  return true;
end;
$$;

create or replace function public.admin_shop_menus_reorder(p_ids bigint[])
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  i integer;
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ACCESS_REQUIRED';
  end if;

  if p_ids is null then
    raise exception 'INVALID_MENU_ORDER';
  end if;

  for i in 1..coalesce(array_length(p_ids, 1), 0) loop
    update public.shop_menus
    set sort_order = i * 10, updated_at = now()
    where id = p_ids[i];
  end loop;

  return true;
end;
$$;

grant execute on function public.admin_shop_menus_list() to authenticated;
grant execute on function public.admin_shop_menu_create(text,text,text,integer) to authenticated;
grant execute on function public.admin_shop_menu_update(bigint,text,text,text,integer,boolean) to authenticated;
grant execute on function public.admin_shop_menu_delete(bigint) to authenticated;
grant execute on function public.admin_shop_menus_reorder(bigint[]) to authenticated;

alter table public.shop_menus enable row level security;

/* No public SELECT policy is intentionally added here.
   The admin RPC is security-definer and checks is_admin(). */

create or replace function public.set_shop_menus_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists shop_menus_updated_at on public.shop_menus;
create trigger shop_menus_updated_at
before update on public.shop_menus
for each row execute function public.set_shop_menus_updated_at();
