create table if not exists public.updates (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  update_type text not null default 'announcement',
  icon text not null default '📢',
  pinned boolean not null default false,
  enabled boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint updates_title_check check (length(trim(title)) between 1 and 120),
  constraint updates_content_check check (length(trim(content)) between 1 and 5000),
  constraint updates_type_check check (update_type in ('announcement','feature','important','maintenance','event'))
);

create index if not exists updates_public_order_idx
  on public.updates (enabled, pinned desc, published_at desc, id desc);

alter table public.updates enable row level security;

create or replace function public.admin_updates_list()
returns table (id bigint,title text,content text,update_type text,icon text,pinned boolean,enabled boolean,published_at timestamptz,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  return query select u.id,u.title,u.content,u.update_type,u.icon,u.pinned,u.enabled,u.published_at,u.created_at,u.updated_at
  from public.updates u order by u.pinned desc,u.published_at desc nulls last,u.id desc;
end; $$;

create or replace function public.admin_updates_create(p_title text,p_content text,p_update_type text default 'announcement',p_icon text default '📢',p_pinned boolean default false,p_enabled boolean default true,p_publish boolean default true)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_id bigint;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  insert into public.updates(title,content,update_type,icon,pinned,enabled,published_at)
  values(trim(p_title),trim(p_content),lower(trim(p_update_type)),coalesce(nullif(trim(p_icon),''),'📢'),coalesce(p_pinned,false),coalesce(p_enabled,true),case when coalesce(p_publish,true) then now() else null end)
  returning id into v_id;
  return v_id;
end; $$;

create or replace function public.admin_updates_update(p_id bigint,p_title text,p_content text,p_update_type text,p_icon text,p_pinned boolean,p_enabled boolean,p_publish boolean)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  update public.updates set title=trim(p_title),content=trim(p_content),update_type=lower(trim(p_update_type)),icon=coalesce(nullif(trim(p_icon),''),'📢'),pinned=coalesce(p_pinned,false),enabled=coalesce(p_enabled,true),published_at=case when coalesce(p_publish,false) then coalesce(published_at,now()) else null end,updated_at=now() where id=p_id;
  if not found then raise exception 'Update not found'; end if;
  return true;
end; $$;

create or replace function public.admin_updates_delete(p_id bigint)
returns boolean language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  delete from public.updates where id=p_id;
  if not found then raise exception 'Update not found'; end if;
  return true;
end; $$;

revoke all on table public.updates from anon,authenticated;
revoke execute on function public.admin_updates_list() from public;
revoke execute on function public.admin_updates_create(text,text,text,text,boolean,boolean,boolean) from public;
revoke execute on function public.admin_updates_update(bigint,text,text,text,text,boolean,boolean,boolean) from public;
revoke execute on function public.admin_updates_delete(bigint) from public;
grant execute on function public.admin_updates_list() to authenticated;
grant execute on function public.admin_updates_create(text,text,text,text,boolean,boolean,boolean) to authenticated;
grant execute on function public.admin_updates_update(bigint,text,text,text,text,boolean,boolean,boolean) to authenticated;
grant execute on function public.admin_updates_delete(bigint) to authenticated;
